# Travis CI Configuration
#
# https://docs.travis-ci.com/
# https://docs.travis-ci.com/user/languages/cpp/
#
# Example with multiple compiler versions, including both GCC and Clang
# https://github.com/facebook/fatal/blob/dev/.travis.yml
#
# OSX Xcode and Clang versions
# https://trac.macports.org/wiki/XcodeVersionInfo


# Test
script:
 - ${CXX} --version && make -j4 && make test

# Always test the master branch, even when there's no pull request
branches:
  only:
    - master

# Test against multiple compiler versions
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-4.9
      env: MATRIX_EVAL="CXX=g++-4.9"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-5
      env: MATRIX_EVAL="CXX=g++-5"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-6
      env: MATRIX_EVAL="CXX=g++-6"
    # Currently fails, issue https://github.com/awdeorio/csvstream/issues/22
    # - os: linux
    #   compiler: gcc
    #   addons:
    #     apt:
    #       sources: ubuntu-toolchain-r-test
    #       packages: g++-7
    #   env: MATRIX_EVAL="CXX=g++-7"
    - os: osx
      osx_image: xcode8.2.1
      env: MATRIX_EVAL="CXX=clang++"
    - os: osx
      osx_image: xcode9.2
      env: MATRIX_EVAL="CXX=clang++"
    - os: osx
      osx_image: xcode10.1
      env: MATRIX_EVAL="CXX=clang++"
before_install:
    - eval "${MATRIX_EVAL}"
